# Even Fibonacci numbers
# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# list_series = []
i = 1
list_series = [0]
while list_series[-1]<4000000:
    if i < 2:
        list_series.append(i)
        i += 1
    else:
        term = list_series[i-1] + list_series[i-2]
        list_series.append(term)
        i += 1
sum_even_series = 0
for i in list_series:
    if i%2 == 0:
        sum_even_series += i
print(sum_even_series)

# answer
# 4613732
